name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.platform}}
    
    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
      - uses: actions/checkout@v3
      - name: Test
        run: go test ./...